name: CI

on:
  push:
    branches:
      - master

jobs:
  lint-test-typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit

    - name: Run ruff (linting)
      run: ruff check .

    - name: Run black (formatting check)
      run: black --check .

    - name: Run isort (import sorting check)
      run: isort --check-only .]

    - name: Run pytest (unit tests)
      run: pytest
  